name: Sync and Build with Upstream
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours to catch new tags
  workflow_dispatch:
    inputs:
      build_current:
        description: 'Build current custom version (ignores upstream check)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    outputs:
      update_needed: ${{ steps.check.outputs.update_needed }}
      latest_tag: ${{ steps.tags.outputs.latest_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add upstream remote
        run: git remote add upstream https://github.com/charmbracelet/crush.git
      
      - name: Fetch upstream tags and branches
        run: |
          git fetch upstream --tags
          git fetch upstream main
      
      - name: Get current and latest tags
        id: tags
        run: |
          CURRENT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          LATEST_TAG=$(git describe --tags --abbrev=0 upstream/main 2>/dev/null || echo "v0.0.0")
          echo "current_tag=$CURRENT_TAG" >> $GITHUB_OUTPUT
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Current: $CURRENT_TAG, Latest: $LATEST_TAG"
      
      - name: Check if update needed
        id: check
        run: |
          if [ "${{ steps.tags.outputs.current_tag }}" = "${{ steps.tags.outputs.latest_tag }}" ] && [ "${{ github.event.inputs.build_current }}" != "true" ]; then
            echo "update_needed=false" >> $GITHUB_OUTPUT
          else
            echo "update_needed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Rebase and tag
        if: steps.check.outputs.update_needed == 'true'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "7470800+sulring@users.noreply.github.com"
          git checkout custom-keyboard-mappings
          git rebase upstream/main
          git push origin custom-keyboard-mappings --force-with-lease
          git tag ${{ steps.tags.outputs.latest_tag }}-custom
          git push origin ${{ steps.tags.outputs.latest_tag }}-custom

  build:
    needs: sync-and-build
    if: needs.sync-and-build.outputs.update_needed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout branch for building
        uses: actions/checkout@v4
        with:
          ref: custom-keyboard-mappings
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          VERSION=${{ needs.sync-and-build.outputs.latest_tag }}
          BINARY_NAME=crush-${{ matrix.goos }}-${{ matrix.goarch }}
          
          if [ "${{ matrix.goos }}" = "windows" ]; then
            BINARY_NAME=${BINARY_NAME}.exe
          fi
          
          go build -ldflags="-X github.com/charmbracelet/crush/internal/version.Version=${VERSION}" -o ${BINARY_NAME} .
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crush-${{ matrix.goos }}-${{ matrix.goarch }}
          path: crush-*