name: Sync with Upstream
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Add upstream remote
        run: git remote add upstream https://github.com/charmbracelet/crush.git
      - name: Fetch upstream
        run: git fetch upstream
      - name: Rebase custom branch onto upstream main
        run: |
          git checkout custom-keyboard-mappings
          git rebase upstream/main
          git push origin custom-keyboard-mappings --force-with-lease